import {
  Box, Terminal, Cloud, Code2, Layers, FileCode, Settings2, ShieldCheck,
  GitBranch, Database, Globe, Package, Monitor, Cpu, Server, Activity,
  Key, BarChart3, Wrench, Zap, Binary,
} from 'lucide-react';

export const downloads = [
  // ── DevOps ─────────────────────────────────────────────────────────────
  {
    id: 'docker-desktop',
    title: 'Docker Desktop',
    shortDescription: 'Build, share, and run containerized apps. Includes Engine, CLI, Compose, and K8s.',
    category: 'DevOps',
    icon: Box,
    os: ['windows', 'macos', 'linux'],
    version: '4.30',
    installCmd: 'brew install --cask docker',
    url: 'https://www.docker.com/products/docker-desktop/',
  },
  {
    id: 'kubectl',
    title: 'kubectl',
    shortDescription: 'Official Kubernetes CLI. Deploy apps, inspect cluster resources, and manage workloads.',
    category: 'DevOps',
    icon: Terminal,
    os: ['windows', 'macos', 'linux'],
    version: '1.30',
    installCmd: 'brew install kubectl',
    url: 'https://kubernetes.io/docs/tasks/tools/',
  },
  {
    id: 'minikube',
    title: 'Minikube',
    shortDescription: 'Single-node Kubernetes cluster for local development and testing.',
    category: 'DevOps',
    icon: Server,
    os: ['windows', 'macos', 'linux'],
    version: '1.33',
    installCmd: 'brew install minikube',
    url: 'https://minikube.sigs.k8s.io/docs/start/',
  },
  {
    id: 'k9s',
    title: 'k9s',
    shortDescription: 'Terminal UI for Kubernetes. Navigate pods, logs, and resources in real-time.',
    category: 'DevOps',
    icon: Monitor,
    os: ['windows', 'macos', 'linux'],
    version: '0.32',
    installCmd: 'brew install k9s',
    url: 'https://k9scli.io/',
  },
  {
    id: 'helm',
    title: 'Helm',
    shortDescription: 'Package manager for Kubernetes. Define, install, and upgrade K8s applications.',
    category: 'DevOps',
    icon: Package,
    os: ['windows', 'macos', 'linux'],
    version: '3.14',
    installCmd: 'brew install helm',
    url: 'https://helm.sh/docs/intro/install/',
  },
  {
    id: 'terraform',
    title: 'Terraform CLI',
    shortDescription: 'Infrastructure as code. Provision cloud resources across AWS, GCP, Azure.',
    category: 'DevOps',
    icon: Cloud,
    os: ['windows', 'macos', 'linux'],
    version: '1.8',
    installCmd: 'brew tap hashicorp/tap && brew install hashicorp/tap/terraform',
    url: 'https://developer.hashicorp.com/terraform/install',
  },
  {
    id: 'ansible',
    title: 'Ansible',
    shortDescription: 'Agentless IT automation for config management and app deployment over SSH.',
    category: 'DevOps',
    icon: Settings2,
    os: ['linux', 'macos'],
    version: '2.16',
    installCmd: 'pip install ansible',
    url: 'https://docs.ansible.com/ansible/latest/installation_guide/',
  },
  {
    id: 'argocd-cli',
    title: 'ArgoCD CLI',
    shortDescription: 'CLI for ArgoCD GitOps continuous delivery tool for Kubernetes.',
    category: 'DevOps',
    icon: GitBranch,
    os: ['windows', 'macos', 'linux'],
    version: '2.11',
    installCmd: 'brew install argocd',
    url: 'https://argo-cd.readthedocs.io/en/stable/cli_installation/',
  },
  {
    id: 'aws-cli',
    title: 'AWS CLI',
    shortDescription: 'Manage all AWS services from command line. Essential for cloud DevOps workflows.',
    category: 'DevOps',
    icon: Cloud,
    os: ['windows', 'macos', 'linux'],
    version: '2.16',
    installCmd: 'brew install awscli',
    url: 'https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html',
  },
  {
    id: 'gcloud',
    title: 'Google Cloud SDK',
    shortDescription: 'CLI for GCP. Includes gcloud, gsutil, bq for GKE, GCS, and BigQuery.',
    category: 'DevOps',
    icon: Globe,
    os: ['windows', 'macos', 'linux'],
    version: '473',
    installCmd: 'brew install --cask google-cloud-sdk',
    url: 'https://cloud.google.com/sdk/docs/install',
  },
  {
    id: 'vault',
    title: 'HashiCorp Vault',
    shortDescription: 'Manage secrets and dynamic credentials securely across environments.',
    category: 'DevOps',
    icon: Key,
    os: ['windows', 'macos', 'linux'],
    version: '1.16',
    installCmd: 'brew tap hashicorp/tap && brew install hashicorp/tap/vault',
    url: 'https://developer.hashicorp.com/vault/downloads',
  },
  {
    id: 'prometheus',
    title: 'Prometheus',
    shortDescription: 'Open-source monitoring toolkit. Scrapes and stores time-series metrics from targets.',
    category: 'DevOps',
    icon: Activity,
    os: ['windows', 'macos', 'linux'],
    version: '2.52',
    installCmd: 'brew install prometheus',
    url: 'https://prometheus.io/download/',
  },
  {
    id: 'grafana',
    title: 'Grafana',
    shortDescription: 'Visualize metrics, logs, and traces in rich dashboards from any data source.',
    category: 'DevOps',
    icon: BarChart3,
    os: ['windows', 'macos', 'linux'],
    version: '10.4',
    installCmd: 'brew install grafana',
    url: 'https://grafana.com/grafana/download',
  },
  {
    id: 'lens',
    title: 'Lens (OpenLens)',
    shortDescription: 'Most powerful Kubernetes IDE. Manage multiple clusters with a visual UI.',
    category: 'DevOps',
    icon: Cpu,
    os: ['windows', 'macos', 'linux'],
    version: '2024',
    installCmd: 'brew install --cask openlens',
    url: 'https://k8slens.dev/',
  },
  {
    id: 'gh-cli',
    title: 'GitHub CLI',
    shortDescription: 'Create PRs, manage issues, trigger workflows, and interact with GitHub from CLI.',
    category: 'DevOps',
    icon: GitBranch,
    os: ['windows', 'macos', 'linux'],
    version: '2.49',
    installCmd: 'brew install gh',
    url: 'https://cli.github.com/',
  },

  // ── SDE Tools ──────────────────────────────────────────────────────────
  {
    id: 'git',
    title: 'Git',
    shortDescription: 'Distributed version control system. The foundation of every modern project.',
    category: 'SDE Tools',
    icon: GitBranch,
    os: ['windows', 'macos', 'linux'],
    version: '2.45',
    installCmd: 'brew install git',
    url: 'https://git-scm.com/downloads',
  },
  {
    id: 'vscode',
    title: 'VS Code',
    shortDescription: 'Fast, extensible editor with IntelliSense, debugging, and 50k+ extensions.',
    category: 'SDE Tools',
    icon: FileCode,
    os: ['windows', 'macos', 'linux'],
    version: '1.89',
    installCmd: 'brew install --cask visual-studio-code',
    url: 'https://code.visualstudio.com/Download',
  },
  {
    id: 'python',
    title: 'Python',
    shortDescription: 'General-purpose language for scripting, ML, automation, APIs, and data.',
    category: 'SDE Tools',
    icon: Code2,
    os: ['windows', 'macos', 'linux'],
    version: '3.12',
    installCmd: 'brew install python@3.12',
    url: 'https://www.python.org/downloads/',
  },
  {
    id: 'nodejs',
    title: 'Node.js',
    shortDescription: 'JavaScript runtime for scalable server-side apps and CLI tooling.',
    category: 'SDE Tools',
    icon: Layers,
    os: ['windows', 'macos', 'linux'],
    version: '20 LTS',
    installCmd: 'brew install node@20',
    url: 'https://nodejs.org/en/download/',
  },
  {
    id: 'golang',
    title: 'Go (Golang)',
    shortDescription: 'Compiled language optimized for cloud infrastructure and microservices.',
    category: 'SDE Tools',
    icon: Zap,
    os: ['windows', 'macos', 'linux'],
    version: '1.22',
    installCmd: 'brew install go',
    url: 'https://go.dev/dl/',
  },
  {
    id: 'rust',
    title: 'Rust',
    shortDescription: 'Systems language focused on safety and speed — no garbage collector.',
    category: 'SDE Tools',
    icon: Cpu,
    os: ['windows', 'macos', 'linux'],
    version: '1.78',
    installCmd: 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh',
    url: 'https://www.rust-lang.org/tools/install',
  },
  {
    id: 'postman',
    title: 'Postman',
    shortDescription: 'API platform for building and testing REST, GraphQL, and SOAP APIs.',
    category: 'SDE Tools',
    icon: Globe,
    os: ['windows', 'macos', 'linux'],
    version: '11',
    installCmd: 'brew install --cask postman',
    url: 'https://www.postman.com/downloads/',
  },
  {
    id: 'dbeaver',
    title: 'DBeaver',
    shortDescription: 'Universal DB GUI. Supports PostgreSQL, MySQL, SQLite, MongoDB, Redis.',
    category: 'SDE Tools',
    icon: Database,
    os: ['windows', 'macos', 'linux'],
    version: '24.1',
    installCmd: 'brew install --cask dbeaver-community',
    url: 'https://dbeaver.io/download/',
  },
  {
    id: 'jq',
    title: 'jq',
    shortDescription: 'Command-line JSON processor. Slice, filter, and transform JSON easily.',
    category: 'SDE Tools',
    icon: Binary,
    os: ['windows', 'macos', 'linux'],
    version: '1.7',
    installCmd: 'brew install jq',
    url: 'https://jqlang.github.io/jq/download/',
  },
  {
    id: 'httpie',
    title: 'HTTPie',
    shortDescription: 'Human-friendly HTTP client for the CLI — great for testing APIs.',
    category: 'SDE Tools',
    icon: Wrench,
    os: ['windows', 'macos', 'linux'],
    version: '3.2',
    installCmd: 'brew install httpie',
    url: 'https://httpie.io/cli',
  },
  {
    id: 'intellij',
    title: 'IntelliJ IDEA CE',
    shortDescription: 'World-class IDE for Java and Kotlin with smart refactoring and analysis.',
    category: 'SDE Tools',
    icon: Monitor,
    os: ['windows', 'macos', 'linux'],
    version: '2024.1',
    installCmd: 'brew install --cask intellij-idea-ce',
    url: 'https://www.jetbrains.com/idea/download/',
  },
  {
    id: 'java-jdk',
    title: 'OpenJDK 21',
    shortDescription: 'LTS Java Development Kit. Run Java, Kotlin, Scala, and Groovy apps.',
    category: 'SDE Tools',
    icon: Code2,
    os: ['windows', 'macos', 'linux'],
    version: '21 LTS',
    installCmd: 'brew install openjdk@21',
    url: 'https://adoptium.net/',
  },
  {
    id: 'azure-cli',
    title: 'Azure CLI',
    shortDescription: 'Manage Azure resources, AKS clusters, and pipelines from the command line.',
    category: 'DevOps',
    icon: Cloud,
    os: ['windows', 'macos', 'linux'],
    version: '2.61',
    installCmd: 'brew install azure-cli',
    url: 'https://learn.microsoft.com/en-us/cli/azure/install-azure-cli',
  },
];
