import {
  Box, Ship, Terminal, GitBranch, Database, Globe, Code2,
  Layers, Settings2, Network, Activity, BookOpen, Cpu, Workflow,
  Cloud, Lock, FileJson, Braces,
} from 'lucide-react';

export const topics = [
  // ── DevOps Track ───────────────────────────────────────────────────────
  {
    id: 'docker',
    slug: 'docker',
    title: 'Docker',
    shortDescription: 'Containerize apps and dependencies for reproducible, portable environments.',
    icon: Box,
    tags: ['containers', 'devops', 'deployment'],
    resources: [
      { title: 'Docker Official Docs', url: 'https://docs.docker.com/', type: 'Official' },
      { title: 'Docker Hub Registry', url: 'https://hub.docker.com/', type: 'Reference' },
      { title: 'Dockerfile Best Practices', url: 'https://docs.docker.com/develop/develop-images/dockerfile_best-practices/', type: 'Guide' },
      { title: 'Docker Compose Overview', url: 'https://docs.docker.com/compose/', type: 'Official' },
      { title: 'Play with Docker (Lab)', url: 'https://labs.play-with-docker.com/', type: 'Playground' },
      { title: 'Docker CLI Cheat Sheet', url: 'https://docs.docker.com/get-started/docker_cheatsheet.pdf', type: 'Cheat Sheet' },
    ],
  },
  {
    id: 'kubernetes',
    slug: 'kubernetes',
    title: 'Kubernetes',
    shortDescription: 'Orchestrate containers at scale with automated deployment, scaling, and healing.',
    icon: Ship,
    tags: ['orchestration', 'devops', 'cloud'],
    resources: [
      { title: 'Kubernetes Official Docs', url: 'https://kubernetes.io/docs/', type: 'Official' },
      { title: 'kubectl Cheat Sheet', url: 'https://kubernetes.io/docs/reference/kubectl/cheatsheet/', type: 'Cheat Sheet' },
      { title: 'K8s Concepts Overview', url: 'https://kubernetes.io/docs/concepts/', type: 'Guide' },
      { title: 'Play with Kubernetes', url: 'https://labs.play-with-k8s.com/', type: 'Playground' },
      { title: 'Helm Charts Hub', url: 'https://artifacthub.io/', type: 'Reference' },
      { title: 'Kubernetes Patterns Book', url: 'https://k8spatterns.io/', type: 'Book' },
    ],
  },
  {
    id: 'terraform',
    slug: 'terraform',
    title: 'Terraform',
    shortDescription: 'Infrastructure as Code — provision and manage cloud resources declaratively.',
    icon: Cloud,
    tags: ['iac', 'devops', 'cloud'],
    resources: [
      { title: 'Terraform Docs', url: 'https://developer.hashicorp.com/terraform/docs', type: 'Official' },
      { title: 'Terraform Registry', url: 'https://registry.terraform.io/', type: 'Reference' },
      { title: 'Terraform Best Practices', url: 'https://www.terraform-best-practices.com/', type: 'Guide' },
      { title: 'Learn Terraform (HashiCorp)', url: 'https://developer.hashicorp.com/terraform/tutorials', type: 'Tutorial' },
      { title: 'Terraform Cheat Sheet', url: 'https://spacelift.io/blog/terraform-commands-cheat-sheet', type: 'Cheat Sheet' },
    ],
  },
  {
    id: 'ci-cd',
    slug: 'ci-cd',
    title: 'CI/CD Pipelines',
    shortDescription: 'Automate builds, tests, and deployments with GitHub Actions, Jenkins, and GitLab CI.',
    icon: Workflow,
    tags: ['automation', 'devops', 'pipelines'],
    resources: [
      { title: 'GitHub Actions Docs', url: 'https://docs.github.com/en/actions', type: 'Official' },
      { title: 'GitHub Actions Marketplace', url: 'https://github.com/marketplace?type=actions', type: 'Reference' },
      { title: 'GitLab CI/CD Docs', url: 'https://docs.gitlab.com/ee/ci/', type: 'Official' },
      { title: 'Jenkins Official Docs', url: 'https://www.jenkins.io/doc/', type: 'Official' },
      { title: 'ArgoCD Getting Started', url: 'https://argo-cd.readthedocs.io/en/stable/getting_started/', type: 'Guide' },
    ],
  },
  {
    id: 'ansible',
    slug: 'ansible',
    title: 'Ansible',
    shortDescription: 'Agentless automation for configuration management, patching, and deployment.',
    icon: Settings2,
    tags: ['automation', 'devops', 'configuration'],
    resources: [
      { title: 'Ansible Docs', url: 'https://docs.ansible.com/', type: 'Official' },
      { title: 'Ansible Galaxy (Roles)', url: 'https://galaxy.ansible.com/', type: 'Reference' },
      { title: 'Ansible Best Practices', url: 'https://docs.ansible.com/ansible/latest/tips_tricks/ansible_tips_tricks.html', type: 'Guide' },
      { title: 'Ansible Cheat Sheet', url: 'https://www.digitalocean.com/community/cheatsheets/how-to-use-ansible-cheat-sheet-guide', type: 'Cheat Sheet' },
    ],
  },
  {
    id: 'linux-bash',
    slug: 'linux-bash',
    title: 'Linux & Bash',
    shortDescription: 'Master the command line — scripting, process management, file systems, and networking.',
    icon: Terminal,
    tags: ['linux', 'scripting', 'cli'],
    resources: [
      { title: 'GNU Bash Manual', url: 'https://www.gnu.org/software/bash/manual/', type: 'Official' },
      { title: 'Linux Command Cheat Sheet', url: 'https://www.guru99.com/linux-commands-cheat-sheet.html', type: 'Cheat Sheet' },
      { title: 'The Linux Command Line (Book)', url: 'https://linuxcommand.org/tlcl.php', type: 'Book' },
      { title: 'Bash Scripting Tutorial', url: 'https://www.shellscript.sh/', type: 'Tutorial' },
      { title: 'ExplainShell.com', url: 'https://explainshell.com/', type: 'Tool' },
      { title: 'tldr Pages (Quick Ref)', url: 'https://tldr.sh/', type: 'Reference' },
    ],
  },
  {
    id: 'networking',
    slug: 'networking',
    title: 'Networking & DNS',
    shortDescription: 'TCP/IP, DNS, subnetting, CIDR, HTTP, load balancers — fundamentals every DevOps needs.',
    icon: Network,
    tags: ['networking', 'devops', 'dns'],
    resources: [
      { title: 'Cloudflare Learning — DNS', url: 'https://www.cloudflare.com/learning/dns/what-is-dns/', type: 'Guide' },
      { title: 'Subnet Calculator Guide', url: 'https://www.subnet-calculator.com/', type: 'Tool' },
      { title: 'TCP/IP Guide (Online)', url: 'http://www.tcpipguide.com/free/index.htm', type: 'Reference' },
      { title: 'HTTP/2 Explained', url: 'https://http2-explained.haxx.se/', type: 'Guide' },
      { title: 'Nginx Config Docs', url: 'https://nginx.org/en/docs/', type: 'Official' },
    ],
  },
  {
    id: 'monitoring',
    slug: 'monitoring',
    title: 'Monitoring & Observability',
    shortDescription: 'Prometheus, Grafana, Loki, Jaeger — observe, alert, and debug production systems.',
    icon: Activity,
    tags: ['monitoring', 'devops', 'observability'],
    resources: [
      { title: 'Prometheus Docs', url: 'https://prometheus.io/docs/introduction/overview/', type: 'Official' },
      { title: 'Grafana Docs', url: 'https://grafana.com/docs/', type: 'Official' },
      { title: 'PromQL Tutorial', url: 'https://prometheus.io/docs/prometheus/latest/querying/basics/', type: 'Tutorial' },
      { title: 'OpenTelemetry Docs', url: 'https://opentelemetry.io/docs/', type: 'Official' },
      { title: 'SRE Workbook (Google)', url: 'https://sre.google/workbook/table-of-contents/', type: 'Book' },
    ],
  },
  {
    id: 'security-devsecops',
    slug: 'security-devsecops',
    title: 'DevSecOps',
    shortDescription: 'Shift security left — SAST, DAST, container scanning, secrets management, and RBAC.',
    icon: Lock,
    tags: ['security', 'devops', 'devsecops'],
    resources: [
      { title: 'OWASP Top 10', url: 'https://owasp.org/www-project-top-ten/', type: 'Reference' },
      { title: 'Trivy (Container Scanner)', url: 'https://aquasecurity.github.io/trivy/', type: 'Tool' },
      { title: 'HashiCorp Vault Docs', url: 'https://developer.hashicorp.com/vault/docs', type: 'Official' },
      { title: 'Falco (Runtime Security)', url: 'https://falco.org/docs/', type: 'Tool' },
      { title: 'DevSecOps Manifesto', url: 'https://www.devsecops.org/', type: 'Guide' },
    ],
  },

  // ── SDE Track ──────────────────────────────────────────────────────────
  {
    id: 'git-github',
    slug: 'git-github',
    title: 'Git & GitHub',
    shortDescription: 'Version control, branching strategies, PRs, code reviews, and GitHub Actions.',
    icon: GitBranch,
    tags: ['git', 'sde', 'collaboration'],
    resources: [
      { title: 'Git Official Docs', url: 'https://git-scm.com/doc', type: 'Official' },
      { title: 'GitHub Docs', url: 'https://docs.github.com/en', type: 'Official' },
      { title: 'Git Cheat Sheet (GitHub)', url: 'https://education.github.com/git-cheat-sheet-education.pdf', type: 'Cheat Sheet' },
      { title: 'Learn Git Branching (Visual)', url: 'https://learngitbranching.js.org/', type: 'Playground' },
      { title: 'Conventional Commits', url: 'https://www.conventionalcommits.org/', type: 'Guide' },
    ],
  },
  {
    id: 'system-design',
    slug: 'system-design',
    title: 'System Design',
    shortDescription: 'Design scalable distributed systems — databases, caching, queues, load balancers.',
    icon: Cpu,
    tags: ['architecture', 'sde', 'distributed'],
    resources: [
      { title: 'System Design Primer (GitHub)', url: 'https://github.com/donnemartin/system-design-primer', type: 'Reference' },
      { title: 'High Scalability Blog', url: 'http://highscalability.com/', type: 'Blog' },
      { title: 'Designing Data-Intensive Apps', url: 'https://dataintensive.net/', type: 'Book' },
      { title: 'ByteByteGo Newsletter', url: 'https://blog.bytebytego.com/', type: 'Blog' },
      { title: 'AWS Architecture Center', url: 'https://aws.amazon.com/architecture/', type: 'Reference' },
    ],
  },
  {
    id: 'rest-apis',
    slug: 'rest-apis',
    title: 'REST APIs',
    shortDescription: 'Design, build, and test REST APIs — HTTP methods, status codes, auth, and OpenAPI.',
    icon: Globe,
    tags: ['api', 'sde', 'http'],
    resources: [
      { title: 'REST API Tutorial', url: 'https://restfulapi.net/', type: 'Tutorial' },
      { title: 'OpenAPI Specification', url: 'https://swagger.io/specification/', type: 'Official' },
      { title: 'HTTP Status Codes Reference', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Status', type: 'Reference' },
      { title: 'Postman Learning Center', url: 'https://learning.postman.com/docs/getting-started/', type: 'Tutorial' },
      { title: 'API Security Best Practices', url: 'https://owasp.org/www-project-api-security/', type: 'Guide' },
    ],
  },
  {
    id: 'databases-sql',
    slug: 'databases-sql',
    title: 'Databases & SQL',
    shortDescription: 'SQL, indexing, query optimization, transactions, NoSQL patterns, and schema design.',
    icon: Database,
    tags: ['database', 'sde', 'sql'],
    resources: [
      { title: 'PostgreSQL Docs', url: 'https://www.postgresql.org/docs/', type: 'Official' },
      { title: 'SQLZoo (Interactive SQL)', url: 'https://sqlzoo.net/', type: 'Playground' },
      { title: 'Use The Index Luke!', url: 'https://use-the-index-luke.com/', type: 'Guide' },
      { title: 'MongoDB Docs', url: 'https://www.mongodb.com/docs/', type: 'Official' },
      { title: 'Redis Docs', url: 'https://redis.io/docs/', type: 'Official' },
      { title: 'SQL Cheat Sheet', url: 'https://www.sqltutorial.org/sql-cheat-sheet/', type: 'Cheat Sheet' },
    ],
  },
  {
    id: 'python',
    slug: 'python',
    title: 'Python',
    shortDescription: 'Scripting, automation, APIs, data processing, and ML fundamentals with Python.',
    icon: Code2,
    tags: ['python', 'sde', 'scripting'],
    resources: [
      { title: 'Python Docs', url: 'https://docs.python.org/3/', type: 'Official' },
      { title: 'Real Python Tutorials', url: 'https://realpython.com/', type: 'Tutorial' },
      { title: 'Python Cheat Sheet', url: 'https://www.pythoncheatsheet.org/', type: 'Cheat Sheet' },
      { title: 'FastAPI Docs', url: 'https://fastapi.tiangolo.com/', type: 'Official' },
      { title: 'Python Package Index (PyPI)', url: 'https://pypi.org/', type: 'Reference' },
    ],
  },
  {
    id: 'javascript-node',
    slug: 'javascript-node',
    title: 'JavaScript & Node.js',
    shortDescription: 'Modern JS, async patterns, Node.js internals, Express, and the npm ecosystem.',
    icon: Layers,
    tags: ['javascript', 'sde', 'backend'],
    resources: [
      { title: 'MDN JavaScript Docs', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', type: 'Official' },
      { title: 'Node.js Docs', url: 'https://nodejs.org/en/docs/', type: 'Official' },
      { title: 'JavaScript Info', url: 'https://javascript.info/', type: 'Tutorial' },
      { title: 'Node.js Best Practices', url: 'https://github.com/goldbergyoni/nodebestpractices', type: 'Guide' },
      { title: 'npm Docs', url: 'https://docs.npmjs.com/', type: 'Reference' },
    ],
  },
  {
    id: 'json-yaml',
    slug: 'json-yaml',
    title: 'JSON & YAML',
    shortDescription: 'Data formats used everywhere — config files, APIs, K8s manifests, and CI pipelines.',
    icon: FileJson,
    tags: ['formats', 'sde', 'devops'],
    resources: [
      { title: 'JSON Spec', url: 'https://www.json.org/json-en.html', type: 'Official' },
      { title: 'YAML Spec', url: 'https://yaml.org/spec/1.2-old/spec.html', type: 'Official' },
      { title: 'JSON Schema Docs', url: 'https://json-schema.org/learn/', type: 'Guide' },
      { title: 'jq Manual', url: 'https://jqlang.github.io/jq/manual/', type: 'Reference' },
      { title: 'YAML Cheat Sheet', url: 'https://quickref.me/yaml.html', type: 'Cheat Sheet' },
    ],
  },
];

export const getTopicBySlug = (slug) => topics.find((t) => t.slug === slug);
