import { lazy } from 'react';
import {
  FileJson,
  Code2,
  Key,
  Lock,
  Hash,
  FileText,
  Link as LinkIcon,
  Clock,
  FileCode2,
  Cpu,
  ShieldCheck,
  Terminal,
  Regex,
  Globe
} from 'lucide-react';

export const tools = [
  {
    id: 'yaml-json',
    slug: 'yaml-json',
    title: 'YAML <-> JSON Converter',
    shortDescription: 'Bidirectional converter between YAML and JSON with real-time sync.',
    longDescription: 'Instantly convert YAML to JSON or vice versa. Editing either side automatically updates the other. Essential for working with Kubernetes manifests, CI/CD pipelines, and configuration files.',
    icon: FileCode2,
    category: 'Encoders / Decoders',
    tags: ['yaml', 'json', 'converter', 'devops', 'config'],
    keywords: ['yaml to json', 'json to yaml', 'yaml json converter'],
    visible: true,
    component: lazy(() => import('./yaml-json')),
  },
  {
    id: 'yaml-validator',
    slug: 'yaml-validator',
    title: 'YAML Validator & Formatter',
    shortDescription: 'Validate YAML syntax and get detailed parsing statistics.',
    longDescription: 'Paste your YAML to immediately detect syntax errors, line numbers, and structural issues. Also provides parsing statistics like total keys, max depth, and root type.',
    icon: ShieldCheck,
    category: 'Formatters',
    tags: ['yaml', 'validate', 'lint', 'devops', 'config'],
    keywords: ['yaml validator', 'check yaml', 'yaml linter'],
    visible: true,
    component: lazy(() => import('./yaml-validator')),
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    title: 'JSON Validator & Formatter',
    shortDescription: 'Format, validate, and minify JSON data.',
    longDescription: 'Easily format and prettify messy JSON strings, or minify them for production. Includes validation to help you catch syntax errors instantly.',
    icon: FileJson,
    category: 'Formatters',
    tags: ['json', 'format', 'minify', 'validate', 'beautify'],
    keywords: ['json formatter', 'json validator', 'beautify json'],
    visible: true,
    component: lazy(() => import('./json-formatter')),
  },
  {
    id: 'base64-converter',
    slug: 'base64-converter',
    title: 'Base64 Encode/Decode',
    shortDescription: 'Encode and decode Base64 strings quickly and securely.',
    longDescription: 'A versatile tool to encode raw text into Base64 or decode Base64 strings back to text. Useful for web developers working with API payloads, data URIs, or simple obfuscation.',
    icon: Code2,
    category: 'Encoders / Decoders',
    tags: ['base64', 'encode', 'decode', 'text', 'converter'],
    keywords: ['base64 encode', 'base64 decode', 'text to base64'],
    visible: true,
    component: lazy(() => import('./base64-converter')),
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    title: 'JWT Encoder/Decoder',
    shortDescription: 'Encode, decode, and verify JSON Web Tokens (JWT) in real-time.',
    longDescription: 'A complete JWT toolkit — paste a token to instantly decode its header, payload, and signature, or craft a new token from scratch. Supports HS256, HS384, and HS512 signing algorithms with live signature verification. Everything runs client-side, so your secrets never leave the browser.',
    icon: Key,
    category: 'Security',
    tags: ['jwt', 'encode', 'decode', 'verify', 'security', 'token', 'auth', 'hmac'],
    keywords: ['jwt encoder', 'jwt decoder', 'jwt encoder decoder', 'decode jwt', 'encode jwt', 'json web token', 'jwt verifier'],
    visible: true,
    component: lazy(() => import('./jwt-decoder')),
  },
  {
    id: 'cidr-calc',
    slug: 'cidr-calc',
    title: 'CIDR Calculator',
    shortDescription: 'Calculate network ranges, subnet masks, and view binary representation.',
    longDescription: 'Input an IP address with CIDR notation (e.g. 192.168.1.0/24) to calculate network address, broadcast address, subnet mask, and usable host range. Features a visual binary breakdown.',
    icon: Hash,
    category: 'Networking',
    tags: ['networking', 'cidr', 'ip', 'subnet', 'devops'],
    keywords: ['cidr calculator', 'subnet calculator', 'ip range'],
    visible: true,
    component: lazy(() => import('./cidr-calc')),
  },
  {
    id: 'cron-parser',
    slug: 'cron-parser',
    title: 'Cron Parser',
    shortDescription: 'Translate cron expressions into human-readable text and next run times.',
    longDescription: 'Understand complex cron schedule expressions at a glance. Translates standard 5-part cron syntax into plain English and simulates the next 5 execution times.',
    icon: Clock,
    category: 'DevOps',
    tags: ['cron', 'schedule', 'devops', 'automation'],
    keywords: ['cron expression', 'cron parser', 'crontab generator'],
    visible: true,
    component: lazy(() => import('./cron-parser')),
  },
  {
    id: 'curl-builder',
    slug: 'curl-builder',
    title: 'cURL Builder',
    shortDescription: 'Visually build API requests and generate copyable cURL commands.',
    longDescription: 'A GUI to build HTTP requests with methods, headers, and bodies. Automatically generates clean, properly escaped cURL and HTTPie commands ready to paste into your terminal.',
    icon: Terminal,
    category: 'Web',
    tags: ['curl', 'http', 'api', 'builder', 'request'],
    keywords: ['curl builder', 'generate curl', 'http request builder'],
    visible: true,
    component: lazy(() => import('./curl-builder')),
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    title: 'Regex Tester',
    shortDescription: 'Write, test, and debug regular expressions in real-time.',
    longDescription: 'A live regular expression testing environment. Input your pattern and flags, evaluate it against test strings, and immediately see matched results. Includes built-in cheat sheets for quick reference.',
    icon: Regex,
    category: 'Text Tools',
    tags: ['regex', 'regular expression', 'test', 'match', 'devops'],
    keywords: ['regex tester', 'regex builder', 'test regex', 'match regex'],
    visible: true,
    component: lazy(() => import('./regex-tester')),
  },
  {
    id: 'api-tester',
    slug: 'api-tester',
    title: 'API Tester',
    shortDescription: 'Send HTTP requests and view responses in real-time.',
    longDescription: 'A complete HTTP client right in your browser. Configure methods, URLs, headers, and bodies, then send requests to instantly view response data. Includes persistent local storage history.',
    icon: Globe,
    category: 'Web',
    tags: ['http', 'api', 'request', 'postman', 'rest'],
    keywords: ['api tester', 'http client', 'send request', 'rest client'],
    visible: true,
    component: lazy(() => import('./api-tester')),
  }
];

export const getToolBySlug = (slug) => tools.find(tool => tool.slug === slug);

export const categories = [...new Set(tools.map(tool => tool.category))];
